title: GDG Bari DevFest
description: > # this means to ignore newlines until "baseurl:"
  GDG DevFest Levante 2018
  25 Agosto - 1  Settembre | DevFest Levante 2018 è un evento tech settimanale estivo: workshop, talks, networking, mare e tanto sole!
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://gdgbari.github.io" # the base hostname & protocol for your site
# Build settings
markdown: kramdown

logo: "../css/2016_style/img/icon-large.png"

social: 
  name: GDG Bari
  link: "https://www.facebook.com/GDGBari"

book:
 form: "https://goo.gl/forms/KVsStXjYEFwBBlYn1"

sponsor:
  form: "https://goo.gl/forms/m6qICpojeed1bfr92"

speaker:
  form:  "https://goo.gl/forms/cPbLUnTtyhVV92Wc2"

google_site_verification: googleXXXXXXXXXXXXXXXX.html

# include: ['_2016_pages', '_2017_pages']
include: ['_2018_pages']

gems:
  - jekyll-sitemap
  - jekyll-seo-tag

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: facebook
    url: https://www.facebook.com/GDGBari/
  - title: telegram
    url: https://t.me/joinchat/CaNX5khR0M7BrTugv5h8gw

# Build settings
markdown: kramdown
permalink: pretty