title: GDG Bari DevFest
description: > # this means to ignore newlines until "baseurl:"
  The Google tech conference in Bari carefully crafted for you by the GDG Bari! 
  A 100% community based event, all about Android, Web, AI, IoT & Cloud!
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://gdgbari.github.io" # the base hostname & protocol for your site
# Build settings
markdown: kramdown

logo: "../css/2016_style/img/icon-large.png"

social: 
  name: GDG Bari
  link: "https://www.facebook.com/GDGBari"

google_site_verification: googleXXXXXXXXXXXXXXXX.html

# include: ['_2016_pages', '_2017_pages']
include: ['_2018_pages']

gems:
  - jekyll-sitemap
  - jekyll-seo-tag

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: facebook
    url: https://www.facebook.com/GDGBari/
  - title: google-plus
    url: https://plus.google.com/+GDGBari

# Build settings
markdown: kramdown
permalink: pretty